services:
  mongo-db-local-test:
    container_name: mongo-db-local-test
    #image: mongodb/mongodb-community-server:6.0.7-ubi8
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
    - '27018:27017'